# Generated by Django 5.1.2 on 2024-10-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenceModel',
            fields=[
                ('sr', models.AutoField(primary_key=True, serialize=False, verbose_name='Sr.')),
                ('spender', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Online', 'Online'), ('UPI', 'UPI')], max_length=100)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Pending', 'Pending')], max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
