# Generated by Django 5.1.2 on 2024-10-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expencemodel',
            options={'ordering': ['sr']},
        ),
    ]
